### PR TITLE
support overlay networks via --gwdev

### PR DESCRIPTION
**Pull request by mbessler**
add support for unison sync over other network interfaces,
such as those provided by overlay networks, for example weave.

### CODE REVIEW

**Comment by brimstone** [comment]
Thanks!

**Comment by mbessler** [comment]
Thanks. Do you have an automated build setup on docker hub...  I could not find one.

**Comment by brimstone** [comment]
Renamed the project to fit convention and created an auto build setup on https://hub.docker.com/r/brimstone/unison/.

**Comment by mbessler** [comment]
Awesome thanks so much.

**Pull request merged**
